font DroidSansMono textures/fonts/DroidSansMono.png DroidSansMono.dat
font Roboto textures/fonts/Roboto.png Roboto.dat
texture background textures/effects/background.png
texture Red-Shield textures/effects/red-shield.png
texture Ship-Default textures/ships/default.png
texture Ship-Red-Battleship textures/ships/red/battleship.png
texture Ship-Red-Interceptor textures/ships/red/interceptor.png
texture Ship-Red-Cruiser textures/ships/red/cruiser.png
texture Ship-Red-EMP textures/ships/red/emp.png
texture Ship-Red-Bomber textures/ships/red/bomber.png
texture Ship-Red-Juggernaut textures/ships/red/juggernaut.png
texture Ship-Red-Mine textures/ships/red/mine.png
texture Ship-Red-Mine-Layer textures/ships/red/mine-layer.png
texture Ship-Red-Support textures/ships/red/support.png
texture Ship-Red-Stealth textures/ships/red/stealth.png
texture Ship-Red-Warp-Gate textures/ships/red/warp-gate.png
texture Ship-Red-Weapons-Platform textures/ships/red/weapons-platform.png
texture Blue-Shield textures/effects/blue-shield.png
texture Ship-Blue-Battleship textures/ships/blue/battleship.png
texture Ship-Blue-Interceptor textures/ships/blue/interceptor.png
texture Ship-Blue-Cruiser textures/ships/blue/cruiser.png
texture Ship-Blue-EMP textures/ships/blue/emp.png
texture Ship-Blue-Bomber textures/ships/blue/bomber.png
texture Ship-Blue-Juggernaut textures/ships/blue/juggernaut.png
texture Ship-Blue-Mine textures/ships/blue/mine.png
texture Ship-Blue-Mine-Layer textures/ships/blue/mine-layer.png
texture Ship-Blue-Support textures/ships/blue/support.png
texture Ship-Blue-Stealth textures/ships/blue/stealth.png
texture Ship-Blue-Warp-Gate textures/ships/blue/warp-gate.png
texture Ship-Blue-Weapons-Platform textures/ships/blue/weapons-platform.png
texture explosion-0 textures/effects/explosion/explosion-1.png
texture explosion-1 textures/effects/explosion/explosion-2.png
texture explosion-2 textures/effects/explosion/explosion-3.png
texture explosion-3 textures/effects/explosion/explosion-4.png
texture explosion-4 textures/effects/explosion/explosion-5.png
texture explosion-5 textures/effects/explosion/explosion-6.png
texture explosion-6 textures/effects/explosion/explosion-7.png
texture explosion-7 textures/effects/explosion/explosion-8.png
texture explosion-8 textures/effects/explosion/explosion-9.png
texture explosion-9 textures/effects/explosion/explosion-10.png
texture explosion-10 textures/effects/explosion/explosion-11.png
texture explosion-11 textures/effects/explosion/explosion-12.png
texture explosion-12 textures/effects/explosion/explosion-13.png
texture explosion-13 textures/effects/explosion/explosion-14.png
texture explosion-14 textures/effects/explosion/explosion-15.png
texture explosion-15 textures/effects/explosion/explosion-16.png
texture explosion-16 textures/effects/explosion/explosion-17.png
texture explosion-17 textures/effects/explosion/explosion-18.png
texture explosion-18 textures/effects/explosion/explosion-19.png
texture explosion-19 textures/effects/explosion/explosion-20.png
texture explosion-20 textures/effects/explosion/explosion-21.png
texture explosion-21 textures/effects/explosion/explosion-22.png
texture explosion-22 textures/effects/explosion/explosion-23.png
texture explosion-23 textures/effects/explosion/explosion-24.png
texture explosion-24 textures/effects/explosion/explosion-25.png
texture explosion-25 textures/effects/explosion/explosion-26.png
texture explosion-26 textures/effects/explosion/explosion-27.png
texture explosion-27 textures/effects/explosion/explosion-28.png
texture explosion-28 textures/effects/explosion/explosion-29.png
texture explosion-29 textures/effects/explosion/explosion-30.png
texture explosion-30 textures/effects/explosion/explosion-31.png
texture explosion-31 textures/effects/explosion/explosion-32.png
texture explosion-32 textures/effects/explosion/explosion-33.png
texture explosion-33 textures/effects/explosion/explosion-34.png
texture explosion-34 textures/effects/explosion/explosion-35.png
texture explosion-35 textures/effects/explosion/explosion-36.png
texture explosion-36 textures/effects/explosion/explosion-37.png
texture explosion-37 textures/effects/explosion/explosion-38.png
texture explosion-38 textures/effects/explosion/explosion-39.png
texture explosion-39 textures/effects/explosion/explosion-40.png
texture explosion-40 textures/effects/explosion/explosion-41.png
texture explosion-41 textures/effects/explosion/explosion-42.png
texture explosion-42 textures/effects/explosion/explosion-43.png
texture explosion-43 textures/effects/explosion/explosion-44.png
texture explosion-44 textures/effects/explosion/explosion-45.png
texture explosion-45 textures/effects/explosion/explosion-46.png
texture explosion-46 textures/effects/explosion/explosion-47.png
texture explosion-47 textures/effects/explosion/explosion-48.png
texture explosion-48 textures/effects/explosion/explosion-49.png
texture explosion-49 textures/effects/explosion/explosion-50.png
texture explosion-50 textures/effects/explosion/explosion-51.png
texture explosion-51 textures/effects/explosion/explosion-52.png
texture explosion-52 textures/effects/explosion/explosion-53.png
texture explosion-53 textures/effects/explosion/explosion-54.png
texture explosion-54 textures/effects/explosion/explosion-55.png
texture explosion-55 textures/effects/explosion/explosion-56.png
texture explosion-56 textures/effects/explosion/explosion-57.png
texture explosion-57 textures/effects/explosion/explosion-58.png
texture explosion-58 textures/effects/explosion/explosion-59.png
texture explosion-59 textures/effects/explosion/explosion-60.png
texture explosion-60 textures/effects/explosion/explosion-61.png
texture explosion-61 textures/effects/explosion/explosion-62.png
texture explosion-62 textures/effects/explosion/explosion-63.png
texture explosion-63 textures/effects/explosion/explosion-64.png
texture explosion-64 textures/effects/explosion/explosion-65.png
texture explosion-65 textures/effects/explosion/explosion-66.png
texture explosion-66 textures/effects/explosion/explosion-67.png
texture explosion-67 textures/effects/explosion/explosion-68.png
texture explosion-68 textures/effects/explosion/explosion-69.png
texture explosion-69 textures/effects/explosion/explosion-70.png
texture explosion-70 textures/effects/explosion/explosion-71.png
texture explosion-71 textures/effects/explosion/explosion-72.png
texture explosion-72 textures/effects/explosion/explosion-73.png
texture explosion-73 textures/effects/explosion/explosion-74.png
texture explosion-74 textures/effects/explosion/explosion-75.png
texture explosion-75 textures/effects/explosion/explosion-76.png
texture explosion-76 textures/effects/explosion/explosion-77.png
texture explosion-77 textures/effects/explosion/explosion-78.png
texture explosion-78 textures/effects/explosion/explosion-79.png
texture explosion-79 textures/effects/explosion/explosion-80.png
texture explosion-80 textures/effects/explosion/explosion-81.png
texture explosion-81 textures/effects/explosion/explosion-82.png
texture explosion-82 textures/effects/explosion/explosion-83.png
texture explosion-83 textures/effects/explosion/explosion-84.png
texture explosion-84 textures/effects/explosion/explosion-85.png
texture explosion-85 textures/effects/explosion/explosion-86.png
texture explosion-86 textures/effects/explosion/explosion-87.png
texture explosion-87 textures/effects/explosion/explosion-88.png
texture explosion-88 textures/effects/explosion/explosion-89.png
texture warp-red textures/effects/red-warp.png
texture warp-blue textures/effects/blue-warp.png
texture emp-red textures/effects/red-emp.png
texture emp-blue textures/effects/blue-emp.png
texture emped-red textures/effects/red-emped.png
texture emped-blue textures/effects/blue-emped.png
texture planet textures/effects/planet.png
fshader testShader shaders/shockwave.frag
fshader post1 shaders/post.frag
texture selected textures/effects/selected.png
texture background-0 textures/backgrounds/1.jpg
texture background-1 textures/backgrounds/2.jpg
texture background-2 textures/backgrounds/3.jpg
texture background-3 textures/backgrounds/4.jpg
texture background-4 textures/backgrounds/5.jpg
texture background-5 textures/backgrounds/6.jpg
texture background-6 textures/backgrounds/7.jpg
texture background-7 textures/backgrounds/8.jpg
texture background-8 textures/backgrounds/9.jpg
texture background-9 textures/backgrounds/10.jpg
texture background-10 textures/backgrounds/11.jpg
texture background-11 textures/backgrounds/12.jpg
texture background-12 textures/backgrounds/13.jpg
texture background-13 textures/backgrounds/14.jpg
texture background-14 textures/backgrounds/15.jpg
texture background-15 textures/backgrounds/16.jpg
texture background-16 textures/backgrounds/17.jpg
texture background-17 textures/backgrounds/18.jpg
texture background-18 textures/backgrounds/19.jpg
texture background-19 textures/backgrounds/20.jpg
texture background-18 textures/backgrounds/19.jpg
