font DroidSansMono textures/fonts/DroidSansMono.png DroidSansMono.dat
texture background textures/effects/background.png
texture Red-Shield textures/effects/red-shield.png
texture Ship-Default textures/ships/default.png
texture Ship-Red-Battleship textures/ships/red/battleship.png
texture Ship-Red-Interceptor textures/ships/red/interceptor.png
texture Ship-Red-Cruiser textures/ships/red/cruiser.png
texture Ship-Red-EMP textures/ships/red/emp.png
texture Ship-Red-Bomber textures/ships/red/bomber.png
texture Ship-Red-Juggernaut textures/ships/red/juggernaut.png
texture Ship-Red-Mine textures/ships/red/mine.png
texture Ship-Red-Mine-Layer textures/ships/red/mine-layer.png
texture Ship-Red-Support textures/ships/red/support.png
texture Ship-Red-Stealth textures/ships/red/stealth.png
texture Ship-Red-Warp-Gate textures/ships/red/warp-gate.png
texture Ship-Red-Weapons-Platform textures/ships/red/weapons-platform.png
texture Blue-Shield textures/effects/blue-shield.png
texture Ship-Blue-Battleship textures/ships/blue/battleship.png
texture Ship-Blue-Interceptor textures/ships/blue/interceptor.png
texture Ship-Blue-Cruiser textures/ships/blue/cruiser.png
texture Ship-Blue-EMP textures/ships/blue/emp.png
texture Ship-Blue-Bomber textures/ships/blue/bomber.png
texture Ship-Blue-Juggernaut textures/ships/blue/juggernaut.png
texture Ship-Blue-Mine textures/ships/blue/mine.png
texture Ship-Blue-Mine-Layer textures/ships/blue/mine-layer.png
texture Ship-Blue-Support textures/ships/blue/support.png
texture Ship-Blue-Stealth textures/ships/blue/stealth.png
texture Ship-Blue-Warp-Gate textures/ships/blue/warp-gate.png
texture Ship-Blue-Weapons-Platform textures/ships/blue/weapons-platform.png
